name: '✨ Feature'
description: '새로운 기능 추가'
title: 'feat: '
labels: ['feature']
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 추가할 기능을 설명해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크리스트로 작성해 주세요.
      placeholder: |
        - [ ] 공통 컴포넌트 사용/추가
        - [ ] API 연동
        - [ ] 상태 처리
    validations:
      required: true
  - type: input
    attributes:
      label: 🎨 Figma
      description: 관련 Figma 화면/노드 링크가 있다면 첨부해 주세요.
      placeholder: https://figma.com/design/...
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
